language: python
before_install:
  - sudo apt update
  - sudo apt install gfortran
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install networkx
  - pip install numpy
  - pip install pandas
  - pip install sympy
  - pip install pytest pytest-cov
  - python setup.py install
script:
  - pytest -v --cache-clear --cov={fsic,fsictools,fsic_fortran} --no-cov-on-fail --cov-branch
  - coverage report -m
