all : figure-3.2.png figures-4.3,4.4.png figures-5.2,5.3,5.4.png figures-6.1t6.7.png figures-6.8t6.11.png figures-7.1t7.5.png figures-9.1t9.3.png

figure-3.2.png : 3_sim.py
	python 3_sim.py

figures-4.3,4.4.png : 4_pc.py
	python 4_pc.py

figures-5.2,5.3,5.4.png : 5_lp1.py
	python 5_lp1.py

figures-6.1t6.7.png : 6_reg.py
	python 6_reg.py

figures-6.8t6.11.png : 6_open.py
	python 6_open.py

figures-7.1t7.5.png : 7_bmw.py
	python 7_bmw.py

figures-9.1t9.3.png : 9_dis.py
	python 9_dis.py
